# Jekyll 사이트 기본 설정
title: "이충언 - 신입 개발자 포트폴리오"
description: "신입 개발자의 포트폴리오 블로그입니다."
baseurl: ""
url: "https://your-username.github.io"
theme: minimal-mistakes-jekyll
minimal_mistakes_skin: "default"

# Markdown & Highlighter 설정
markdown: kramdown
highlighter: rouge

# Permalinks (글 주소 설정)
permalink: /:categories/:title/

# Plugins (Jekyll 필수 플러그인)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

# Pagination (페이지네이션 설정)
paginate: 5
paginate_path: /page:num/

# `_posts`에 작성한 글이 적용되도록 설정
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      share: true
      related: true
